// <auto-generated />
using System;
using AgentMonitorAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentMonitorAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829181625_AddShadowRuleEvaluationTable")]
    partial class AddShadowRuleEvaluationTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AgentMonitorAPI.Models.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastAuthenticatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("Agents", (string)null);
                });

            modelBuilder.Entity("AgentMonitorAPI.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("AgentMonitorAPI.Models.DashboardUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("DashboardUsers", (string)null);
                });

            modelBuilder.Entity("AgentMonitorAPI.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("HealthScore")
                        .HasColumnType("int");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("OperatingSystemVersion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProcessorName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("TotalMemoryBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeviceIdentifier")
                        .IsUnique();

                    b.HasIndex("Hostname");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("AgentMonitorAPI.Models.HealthCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<long>("AvailableMemoryBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("DiskUsagePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("HealthScore")
                        .HasColumnType("int");

                    b.Property<string>("InstalledSoftwareJson")
                        .HasColumnType("json");

                    b.Property<bool?>("IsAntivirusEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsAntivirusInstalled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsAntivirusUpToDate")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsWindowsActivated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IssuesJson")
                        .HasColumnType("json");

                    b.Property<DateTime?>("LastWindowsUpdateAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LoggedOnUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NetworkConfigurationJson")
                        .HasColumnType("json");

                    b.Property<int>("PendingUpdatesCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("SystemDriveFreeBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("SystemDriveTotalBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalMemoryBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "CollectedAtUtc");

                    b.ToTable("HealthChecks", (string)null);
                });

            modelBuilder.Entity("AgentMonitorAPI.Models.MonitoringRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ConsecutiveChecks")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Threshold")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Metric");

                    b.HasIndex("Mode");

                    b.ToTable("MonitoringRules", (string)null);
                });

            modelBuilder.Entity("AgentMonitorAPI.Models.RuleSimulationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AffectedDevices")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EstimatedIncidents")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HealthChecksAnalyzed")
                        .HasColumnType("int");

                    b.Property<Guid>("MonitoringRuleId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("NoiseScorePercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("RecommendedConsecutiveChecks")
                        .HasColumnType("int");

                    b.Property<decimal?>("RecommendedThreshold")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("ToUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TransientIncidents")
                        .HasColumnType("int");

                    b.Property<int>("TriggeredChecks")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MonitoringRuleId");

                    b.ToTable("RuleSimulationRuns");
                });

            modelBuilder.Entity("AgentMonitorAPI.Models.ShadowRuleEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("ConditionMet")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ConsecutiveCount")
                        .HasColumnType("int");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EvaluatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("HealthCheckId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("MetricValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("MonitoringRuleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("RequiredConsecutiveChecks")
                        .HasColumnType("int");

                    b.Property<decimal>("Threshold")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("WouldTriggerIncident")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("HealthCheckId");

                    b.HasIndex("MonitoringRuleId", "DeviceId", "EvaluatedAtUtc");

                    b.ToTable("ShadowRuleEvaluations", (string)null);
                });

            modelBuilder.Entity("AgentMonitorAPI.Models.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("DetectionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("HealthCheckId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LastDetectedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("HealthCheckId");

                    b.HasIndex("LastDetectedAtUtc");

                    b.HasIndex("DeviceId", "Status");

                    b.HasIndex("Status", "Severity");

                    b.HasIndex("DeviceId", "RuleCode", "Status");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("AgentMonitorAPI.Models.Agent", b =>
                {
                    b.HasOne("AgentMonitorAPI.Models.Device", "Device")
                        .WithOne("Agent")
                        .HasForeignKey("AgentMonitorAPI.Models.Agent", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("AgentMonitorAPI.Models.HealthCheck", b =>
                {
                    b.HasOne("AgentMonitorAPI.Models.Device", "Device")
                        .WithMany("HealthChecks")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("AgentMonitorAPI.Models.RuleSimulationRun", b =>
                {
                    b.HasOne("AgentMonitorAPI.Models.MonitoringRule", "MonitoringRule")
                        .WithMany("SimulationRuns")
                        .HasForeignKey("MonitoringRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoringRule");
                });

            modelBuilder.Entity("AgentMonitorAPI.Models.ShadowRuleEvaluation", b =>
                {
                    b.HasOne("AgentMonitorAPI.Models.MonitoringRule", "MonitoringRule")
                        .WithMany()
                        .HasForeignKey("MonitoringRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoringRule");
                });

            modelBuilder.Entity("AgentMonitorAPI.Models.Ticket", b =>
                {
                    b.HasOne("AgentMonitorAPI.Models.Device", "Device")
                        .WithMany("Tickets")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgentMonitorAPI.Models.HealthCheck", "HealthCheck")
                        .WithMany("Tickets")
                        .HasForeignKey("HealthCheckId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");

                    b.Navigation("HealthCheck");
                });

            modelBuilder.Entity("AgentMonitorAPI.Models.Device", b =>
                {
                    b.Navigation("Agent");

                    b.Navigation("HealthChecks");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("AgentMonitorAPI.Models.HealthCheck", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("AgentMonitorAPI.Models.MonitoringRule", b =>
                {
                    b.Navigation("SimulationRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
